name: trivy-security-scanning
on: push

jobs:

  chart-test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # To upload sarif files
    steps:
      - name: Checkout
        uses: actions/checkout@3.5.2 # tag=v3.1.0

      - name: Set up Helm
        uses: helm/chart-testing-action@v2.4.0 # tag=v3.4

      - name: Set up python
        uses: actions/setup-python@v4.6.0 # tag=v4.3.0

      - name: Run Trivy vulnerability scanner in IaC mode ULM
        uses: aquasecurity/trivy-action@master # tag=0.8.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          scan-ref: 'charts/helmdptest'
          output: 'trivy-results1.sarif'
          exit-code: 0
        # severities of vulnerabilities to be displayed
          severity: UNKNOWN,LOW,MEDIUM
          ignore-unfixed: true

      - name: Run Trivy vulnerability scanner in IaC mode HC
        uses: aquasecurity/trivy-action@master # tag=0.8.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          scan-ref: 'charts/helmdptest'
          output: 'trivy-results2.sarif'
          exit-code: 0
        # severities of vulnerabilities to be displayed
          severity: HIGH, CRITICAL
          ignore-unfixed: true
          
      - name: Upload Trivy scan results to GitHub Security tab UML
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results1.sarif'
          category: Trivy UML
          
      - name: Upload Trivy scan results to GitHub Security tab CH
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results2.sarif'
          category: Trivy CH
